services:
  web:
    build: .
    image: danielsdev81/ead-netflix
    depends_on:
      - db
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    environment:
      DB_HOST: db
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      NODE_ENV: "development"
    networks:
      - onebitflix_container_db
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "8990:5432"
    networks:
      - onebitflix_container_db
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  onebitflix_container_db:
    driver: bridge

volumes:
  db_data:
