services:
  web:
    build: .
    image: node:22
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
       DB_HOST: db
       DB_DATABASE: ${DB_DATABASE}
       DB_USERNAME: postgres
       DB_PASSWORD: postgres
       NODE_ENV: "development"
    networks:
      - onebitflix_container_db
    env_file:
      - .env

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "8990:5432"
    networks:
      - onebitflix_container_db
    env_file:
      - .env

networks:
  onebitflix_container_db:
    driver: bridge
